#
# This Makefile was generated by Code::Blocks IDE.
#

SRCS_fd1 = \
AnalyticSolution2D.f \
Coefficients.f \
CustomDouble.f \
Geometry.f \
Properties.f \
Results.f \
Solver.f \
Testing.f \
main.f 

OBJS_fd1 = \
AnalyticSolution2D.o \
Coefficients.o \
CustomDouble.o \
Geometry.o \
Properties.o \
Results.o \
Solver.o \
Testing.o \
main.o 

SRC_DIR_fd1 = src/
OBJS_DIR = obj/Debug/src/
EXE_DIR = bin/Debug/

EXE = MTFDTrab1.exe
FC = gfortran.exe
LD = gfortran.exe
IDIR = 
CFLAGS = -fimplicit-none -ffree-line-length-none -ffixed-line-length-none -ffixed-form -Wall -fallow-argument-mismatch -fimplicit-none -ffree-line-length-none -ffixed-line-length-none -fdefault-integer-8 -fdefault-double-8 -fdefault-real-8 -ffixed-form -Wall -fcheck=bounds -fcheck=all -g  -J$(OBJS_DIR) $(IDIR)
LFLAGS = -static-libgcc -Wl,-Bstatic -lstdc++ -lgfortran -lquadmath -Wl,-Bdynamic -lm 
LIBS = 

VPATH = $(SRC_DIR_fd1):$(OBJS_DIR)
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_fd1))

all : $(EXE)

$(EXE) : $(OBJS_fd1)
	@mkdir -p $(EXE_DIR)
	$(LD) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJS_fd1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_fd1)$(@:.o=.f) -o $(OBJS_DIR)$@

clean :
	rm -f $(OBJS_DIR)*.*
	rm -f $(EXE_DIR)$(EXE)

# File dependencies
AnalyticSolution2D.o: \
    AnalyticSolution2D.f
Coefficients.o: \
    Coefficients.f \
    Properties.o
CustomDouble.o: \
    CustomDouble.f
Geometry.o: \
    Geometry.f
Properties.o: \
    Properties.f
Results.o: \
    Results.f
Solver.o: \
    Solver.f \
    AnalyticSolution2D.o \
    Properties.o
Testing.o: \
    Testing.f \
    AnalyticSolution2D.o \
    Coefficients.o \
    CustomDouble.o \
    Geometry.o \
    Results.o \
    Solver.o
main.o: \
    main.f \
    AnalyticSolution2D.o \
    Coefficients.o \
    Geometry.o \
    Solver.o

